name: Release

on:
  release:
    types: [published]

jobs:

  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: check version
        run: |
          CARGO_VERSION="v$(egrep '^version\s+=' Cargo.toml | egrep -o '[0-9]+\.[0-9]+\.[0-9]+')"
          GIT_VERSION=$(echo "$GITHUB_REF" | egrep -o 'v[0-9]+\.[0-9]+\.[0-9]+')
          echo cargo=$CARGO_VERSION git=$GIT_VERSION
          [ "$GIT_VERSION" = "$CARGO_VERSION" ]
    
  release:
    name: release ${{ matrix.target }}
    needs: check-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
          - target: aarch64-unknown-linux-musl
            archive: tar.gz
    steps:
      - uses: actions/checkout@master
      
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      
      - name: Build
        run: |
          cross build --release --target ${{ matrix.target }}
          cd target/${{ matrix.target }}/release
          tar czf ../../../git-remote-s3-${{ matrix.target }}.tar.gz git-remote-s3
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: git-remote-s3-${{ matrix.target }}.tar.gz
          asset_name: git-remote-s3-${{ matrix.target }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
